### ISSUE TITLE
Mod creator (MCreator for Isle of Ansur :P) and datagen

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#10]
Since IoA mods are basically text only, it could be some way to simplify generating of those by datagen.

This would not only make it - maybe - a bit easier to handle generated features (by writing them in code/dictionaries used in code and converting into .jsons), but also could be useful for much easier mod support in later date.
It would be some sort of core-build MCreator for IoA :P

**Comment by ErdeiFarkasGyula** [comment]
:O mod creation?

**Comment by Toma400** [comment]
Yup, you can create mods by writing your own .jsons :D
I explained that [in wiki page](https://github.com/Toma400/The_Isle_of_Ansur/wiki/Main-Mod-Types). Currently only statpacks are possible (so you can make new races/classes), but I will expand that in the future!

**Comment by AquexTheSeal** [comment]
Make ioa take every player's ip and give them to me

**Comment by Toma400** [comment]
Moved to #28.
